# Generated by Django 5.0.3 on 2024-03-15 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatosGlobales",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("variable", models.CharField(max_length=100)),
                ("anio", models.IntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownAreas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownCapacitaciones",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownCarreras",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownContratoOpcion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownEmpleoSituacion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownEmpleoTipo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownEspecializaciones",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownInstituciones",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownNivelEducativo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownProyecto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownRegimenAseguramiento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownRegimenLaboral",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownRoles",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownRolProyecto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownSedes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownSituacionesEspeciales",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DropdownTipoContrato",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("dleg", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("usuario_nombres", models.CharField(max_length=100)),
                ("usuario_apellidos", models.CharField(max_length=100)),
                ("usuario_correo", models.EmailField(max_length=254, unique=True)),
                ("usuario_contrasenia", models.CharField(max_length=100)),
                (
                    "usuario_sexo",
                    models.CharField(
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Femenino", "Femenino"),
                            ("NE", "No Especificado"),
                        ],
                        default="NE",
                        max_length=15,
                    ),
                ),
                ("usuario_telefono", models.CharField(max_length=50)),
                ("activo", models.BooleanField(default=True)),
                (
                    "id_usuario_rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdownroles",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "usuario_relacionado",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.usuario",
                    ),
                ),
                ("trabajador_tipo_documento", models.CharField(max_length=100)),
                (
                    "trabajador_nacionalidad",
                    models.CharField(default="No Especificado", max_length=100),
                ),
                ("trabajador_fecha_nacimiento", models.DateField()),
                (
                    "trabajador_ubigeo",
                    models.CharField(default="No Especificado", max_length=255),
                ),
                ("trabajador_telefono", models.CharField(max_length=100)),
                (
                    "trabajador_sexo",
                    models.CharField(
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Femenino", "Femenino"),
                            ("No Especificado", "No Especificado"),
                        ],
                        default="No Especificado",
                        max_length=15,
                    ),
                ),
                (
                    "trabajador_estado_civil",
                    models.CharField(
                        choices=[
                            ("Soltero", "Soltero"),
                            ("Casado", "Casado"),
                            ("Viudo", "Viudo"),
                            ("Divorciado", "Divorciado"),
                            ("Conviviente", "Conviviente"),
                            ("No Especificado", "No Especificado"),
                        ],
                        default="No Especificado",
                        max_length=15,
                    ),
                ),
                ("trabajador_fecha_ingreso", models.DateField()),
                (
                    "trabajador_fecha_ingreso_sistema",
                    models.DateField(auto_now_add=True),
                ),
                ("trabajador_edad", models.IntegerField(blank=True, null=True)),
                (
                    "trabajador_record",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "trabajador_exp_previa",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "trabajador_total_anios_exp",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sueldo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sueldo_valor_basico",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "sueldo_asigfam_porcentaje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "sueldo_asignacion_familiar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "sueldo_bono_porcentaje",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "sueldo_monto_bono",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "sueldo_mensual",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("sueldo_anual", models.DecimalField(decimal_places=2, max_digits=20)),
                ("activo", models.BooleanField(default=True)),
                (
                    "trabajador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sueldo",
                        to="api.trabajador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estudio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("estudio_fecha_colegiatura", models.DateField(blank=True, null=True)),
                (
                    "estudio_condicion",
                    models.CharField(
                        choices=[
                            ("Habilitado", "Habilitado"),
                            ("No habilitado", "No habilitado"),
                            ("XXXXX", "XXXXX"),
                        ],
                        default="XXXXX",
                        max_length=15,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "id_carrera_educativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdowncarreras",
                    ),
                ),
                (
                    "id_estudio_capacitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdowncapacitaciones",
                    ),
                ),
                (
                    "id_estudio_especializacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdownespecializaciones",
                    ),
                ),
                (
                    "id_estudio_nivel_educativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdownniveleducativo",
                    ),
                ),
                (
                    "id_estudio_situacion_especial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdownsituacionesespeciales",
                    ),
                ),
                (
                    "id_institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdowninstituciones",
                    ),
                ),
                (
                    "id_regimen_aseguramiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdownregimenaseguramiento",
                    ),
                ),
                (
                    "id_regimen_laboral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdownregimenlaboral",
                    ),
                ),
                (
                    "id_sede_colegiatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdownsedes",
                    ),
                ),
                (
                    "trabajador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudio",
                        to="api.trabajador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("direccion_pais", models.CharField(max_length=255)),
                ("direccion_departamento", models.CharField(max_length=255)),
                ("direccion_provincia", models.CharField(max_length=255)),
                ("direccion_distrito", models.CharField(max_length=255)),
                ("direccion_detalle", models.CharField(max_length=255)),
                ("activo", models.BooleanField(default=True)),
                (
                    "trabajador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direccion",
                        to="api.trabajador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cuenta_bancaria_sueldo_codigo_cci",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cuenta_bancaria_sueldo_codigo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cuenta_bancaria_sueldo_banco",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cuenta_bancaria_cts_codigo_cci",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cuenta_bancaria_cts_codigo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cuenta_bancaria_cts_banco",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "trabajador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuenta_bancaria",
                        to="api.trabajador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "empleo_departamento",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                ("empleo_cargo", models.CharField(default=None, max_length=100)),
                ("activo", models.BooleanField(default=True)),
                (
                    "id_empleo_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdownareas",
                    ),
                ),
                (
                    "id_contrato_opcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdowncontratoopcion",
                    ),
                ),
                (
                    "id_empleo_situacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdownempleosituacion",
                    ),
                ),
                (
                    "id_empleo_tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdownempleotipo",
                    ),
                ),
                (
                    "id_empleo_proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdownproyecto",
                    ),
                ),
                (
                    "id_empleo_proyecto_rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdownrolproyecto",
                    ),
                ),
                (
                    "id_contrato_tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dropdowntipocontrato",
                    ),
                ),
                (
                    "trabajador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrato",
                        to="api.trabajador",
                    ),
                ),
            ],
        ),
    ]
