# Generated by Django 5.0.3 on 2024-03-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="usuario_apellidos",
            new_name="usuario_apellido_paterno",
        ),
        migrations.AddField(
            model_name="usuario",
            name="usuario_apellidos_materno",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
    ]
