# Generated by Django 5.0.3 on 2024-03-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sueldo",
            name="sueldo_anual",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="sueldo",
            name="sueldo_asigfam_porcentaje",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sueldo",
            name="sueldo_asignacion_familiar",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sueldo",
            name="sueldo_mensual",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="sueldo",
            name="sueldo_monto_bono",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
