# Generated by Django 5.0.3 on 2024-03-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0002_rename_usuario_apellidos_usuario_usuario_apellido_paterno_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="usuario_apellidos_materno",
        ),
        migrations.AddField(
            model_name="usuario",
            name="usuario_apellido_materno",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
    ]
