# Generated by Django 4.2.7 on 2023-11-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.CharField(max_length=20)),
                ('cuenta_bancaria_sueldo_codigo_cci', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_bancaria_sueldo_codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_bancaria_sueldo_banco', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_bancaria_cts_codigo_cci', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_bancaria_cts_codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_bancaria_cts_banco', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cuenta_bancaria',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.CharField(max_length=20)),
                ('direccion_pais', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_detalle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='DropdownAreas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dropdown_areas',
            },
        ),
        migrations.CreateModel(
            name='DropdownCapacitaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacitacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dropdown_capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='DropdownCarreras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dropdown_carreras',
            },
        ),
        migrations.CreateModel(
            name='DropdownContratoOpcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opcion_contrato', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dropdown_contrato_opcion',
            },
        ),
        migrations.CreateModel(
            name='DropdownEmpleoSituacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacion_empleo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dropdown_empleo_situacion',
            },
        ),
        migrations.CreateModel(
            name='DropdownEmpleoTipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_empleo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dropdown_empleo_tipo',
            },
        ),
        migrations.CreateModel(
            name='DropdownEspecializaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especializacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dropdown_especializaciones',
            },
        ),
        migrations.CreateModel(
            name='DropdownInstituciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dropdown_instituciones',
            },
        ),
        migrations.CreateModel(
            name='DropdownNivelEducativo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_educativo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dropdown_nivel_educativo',
            },
        ),
        migrations.CreateModel(
            name='DropdownProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dropdown_proyecto',
            },
        ),
        migrations.CreateModel(
            name='DropdownRegimenAseguramiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regimen_aseguramiento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dropdown_regimen_aseguramiento',
            },
        ),
        migrations.CreateModel(
            name='DropdownRegimenLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regimen_laboral', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dropdown_regimen_laboral',
            },
        ),
        migrations.CreateModel(
            name='DropdownRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'dropdown_roles',
            },
        ),
        migrations.CreateModel(
            name='DropdownRolProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_titulo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dropdown_rol_proyecto',
            },
        ),
        migrations.CreateModel(
            name='DropdownSedes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sede', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dropdown_sedes',
            },
        ),
        migrations.CreateModel(
            name='DropdownSituacionesEspeciales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacion_especial', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dropdown_situaciones_especiales',
            },
        ),
        migrations.CreateModel(
            name='DropdownTipoContrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('dleg', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dropdown_tipo_contrato',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('usuario_nombres', models.CharField(max_length=100)),
                ('usuario_apellidos', models.CharField(max_length=100)),
                ('usuario_correo', models.EmailField(max_length=254, unique=True)),
                ('usuario_contrasenia', models.CharField(max_length=100)),
                ('id_usuario_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.dropdownroles')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('usuario_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trabajadores.usuario')),
                ('trabajador_tipo_documento', models.CharField(max_length=100)),
                ('trabajador_path_documento', models.CharField(default='PATH/noNe', max_length=255)),
                ('trabajador_nacionalidad', models.CharField(default='No Especificado', max_length=100)),
                ('trabajador_fecha_nacimiento', models.DateField()),
                ('trabajador_ubigeo', models.CharField(default='No Especificado', max_length=255)),
                ('trabajador_telefono', models.CharField(max_length=100)),
                ('trabajador_sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No Especificado', 'No Especificado')], default='No Especificado', max_length=20)),
                ('trabajador_estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado'), ('Conviviente', 'Conviviente'), ('No Especificado', 'No Especificado')], default='No Especificado', max_length=20)),
                ('trabajador_path_doc_estado_civil', models.CharField(default='PATH/noNe', max_length=255)),
                ('trabajador_fecha_ingreso_sistema', models.DateField(null=True)),
                ('trabajador_fecha_ingreso', models.DateField()),
                ('trabajador_edad', models.IntegerField()),
                ('trabajador_record', models.DecimalField(decimal_places=2, max_digits=20)),
                ('trabajador_exp_previa', models.DecimalField(decimal_places=2, max_digits=20)),
                ('trabajador_total_anios_exp', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'trabajador',
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.CharField(max_length=20)),
                ('estudio_fecha_colegiatura', models.DateField(blank=True, null=True)),
                ('estudio_condicion', models.CharField(default='XXXXX', max_length=15)),
                ('id_carrera_educativa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdowncarreras')),
                ('id_estudio_capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdowncapacitaciones')),
                ('id_estudio_especializacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdownespecializaciones')),
                ('id_estudio_nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdownniveleducativo')),
                ('id_estudio_situacion_especial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdownsituacionesespeciales')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdowninstituciones')),
                ('id_regimen_aseguramiento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdownregimenaseguramiento')),
                ('id_regimen_laboral', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdownregimenlaboral')),
                ('id_sede_colegiatura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdownsedes')),
            ],
            options={
                'db_table': 'estudio',
            },
        ),
        migrations.CreateModel(
            name='Sueldo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo_valor_basico', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sueldo_asigfam_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sueldo_asignacion_familiar', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sueldo_bono_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sueldo_monto_bono', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sueldo_mensual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sueldo_anual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
            ],
            options={
                'db_table': 'sueldo',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empleo_departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('empleo_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('id_contrato_opcion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdownempleotipo')),
                ('id_contrato_tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdowntipocontrato')),
                ('id_empleo_area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdownareas')),
                ('id_empleo_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdownproyecto')),
                ('id_empleo_proyecto_rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdownrolproyecto')),
                ('id_empleo_situacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdownempleosituacion')),
                ('id_empleo_tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajadores.dropdowncontratoopcion')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
    ]
